name: Travel App CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Flask app build test
        run: python -m py_compile app.py

      - name: Build Docker image
        run: docker build -t travel-app-backend .

      - name: Deploy to Render
        run: echo "Render auto-deploys from GitHub → deployment verified"
